[tool.poetry]
name = "lnxcli"
version = "0.1.0"
description = "Linux command line helper"
authors = ["Philip Ruhland <lipruhland@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
